### ISSUE TITLE
适配黑色模式

### ISSUE THREAD

**Issue by githubkill** [frostime/sy-bq-callout#12]
可否适配黑色模式，積読主题
![image](https://github.com/user-attachments/assets/8b049d21-e11d-4fe0-a4b9-803e2e3b1360)

**Comment by frostime** [comment]
你说的适配是什么意思。Callout 在 Tsundoku 主题下是正常的。

![image](https://github.com/user-attachments/assets/499c8721-63d8-4df9-a7e4-e41225e158f6)

**Comment by githubkill** [comment]
> 你说的适配是什么意思。Callout 在 Tsundoku 主题下是正常的。
> 
> ![image](https://private-user-images.githubusercontent.com/27268127/368013318-499c8721-63d8-4df9-a7e4-e41225e158f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTAzMDEsIm5iZiI6MTcyNjU1MDAwMSwicGF0aCI6Ii8yNzI2ODEyNy8zNjgwMTMzMTgtNDk5Yzg3MjEtNjNkOC00ZGY5LWE3ZTQtZTQxMjI1ZTE1OGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA1MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDQ1ODdlYmEzNDBiOTE0MTAxYWY2ZmY4NzA4NTQ4MmI4ZDVhN2ZhYjRjZWFiYmMzMWI0YzA0Yzg1ZjU0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EcHdBe3gKJZIo2SzGz_EsoSyCYF4Hxhk9p6FtbiV_sg)

![image](https://github.com/user-attachments/assets/2dd03b96-6778-4353-912c-0dd6260daf74)
你好，单样式的图标太大了

**Comment by githubkill** [comment]
> > 你说的适配是什么意思。Callout 在 Tsundoku 主题下是正常的。
> > ![image](https://private-user-images.githubusercontent.com/27268127/368013318-499c8721-63d8-4df9-a7e4-e41225e158f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTAzMDEsIm5iZiI6MTcyNjU1MDAwMSwicGF0aCI6Ii8yNzI2ODEyNy8zNjgwMTMzMTgtNDk5Yzg3MjEtNjNkOC00ZGY5LWE3ZTQtZTQxMjI1ZTE1OGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA1MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDQ1ODdlYmEzNDBiOTE0MTAxYWY2ZmY4NzA4NTQ4MmI4ZDVhN2ZhYjRjZWFiYmMzMWI0YzA0Yzg1ZjU0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EcHdBe3gKJZIo2SzGz_EsoSyCYF4Hxhk9p6FtbiV_sg)
> 
> ![image](https://private-user-images.githubusercontent.com/66041112/368014064-2dd03b96-6778-4353-912c-0dd6260daf74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTAzOTksIm5iZiI6MTcyNjU1MDA5OSwicGF0aCI6Ii82NjA0MTExMi8zNjgwMTQwNjQtMmRkMDNiOTYtNjc3OC00MzUzLTkxMmMtMGRkNjI2MGRhZjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA1MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwM2QwMDRhMjYyOGVlZWNhNzA0ZjMzYWFmNGQ0MjEwNWUyMWE2ODA4MTE0M2U1NjZlZTA1MmIyYzRmOTkyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aW93fGTd5C_xYGgwyU0NgOmB3tGUXkbJqeTmxjL2wmM) 你好，单样式的图标太大了

并且感觉块背景太淡了，对比度不太明显，可以参考下飞书的黑色主题的块样式

**Comment by frostime** [comment]
1. 图标显示主要是 emoji 字体的缘故，请在集市里面下载 Emoji 字体插件
2. 颜色可以自行在设置中进行调整

![image](https://github.com/user-attachments/assets/c2ab26d1-81cc-4014-a2ba-53853475081d)

![image](https://github.com/user-attachments/assets/a46202a5-ee9b-46c7-9dc7-334a32a7f900)

你提到的这些在插件的说明文档里面有解释，请先阅读文档解决。

此 issue 先关闭，还有问题可以继续在这里问。
