### ISSUE TITLE
图标主题与Noto图标插件冲突

### ISSUE THREAD

**Issue by zuoez02** [frostime/sy-bq-callout#4]
建议移除index.sass中关于图标主题"Twitter Emoji"的控制，让用户自己选吧，没准还有两个插件都不用的

**Comment by frostime** [comment]
冲突的具体表现形式是啥？

我是由于有些主题里面把引述块的字体写死了，导致安装了图标插件也显示不出来，才不得已加上的。

**Comment by zuoez02** [comment]
装了noto，刷新之后插件不生效图标，得开关图标插件才有效果。就是覆盖的问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Frostime ***@***.***>
发送时间: Tuesday, January 2, 2024 10:44:51 PM
收件人: frostime/sy-bq-callout ***@***.***>
抄送: Luto Yvan ***@***.***>; Author ***@***.***>
主题: Re: [frostime/sy-bq-callout] 图标主题与Noto图标插件冲突 (Issue #4)


冲突的具体表现形式是啥？

我是由于有些主题里面把引述块的字体写死了，导致安装了图标插件也显示不出来，才不得已加上的。

―

**Comment by frostime** [comment]
我想想看怎么解决
