### ISSUE TITLE
中文翻译

### ISSUE THREAD

**Issue by TCOTC** [frostime/sy-bq-callout#5]
各种地方需要中文：

![image](https://github.com/frostime/sy-bq-callout/assets/78434827/b5344f6a-8e9b-43c5-b18e-f86811a2d4a9)

![image](https://github.com/frostime/sy-bq-callout/assets/78434827/b59920d4-fee6-4815-8b15-a9ce8a5a0b6b)

**Comment by frostime** [comment]
按钮的好说，但是 callout 标题显示的是他的 ID，那个不做翻译。

**Comment by TCOTC** [comment]
我感觉翻译会比较容易看，写味就是中文：

![image](https://github.com/frostime/sy-bq-callout/assets/78434827/bb088c13-995a-4d5e-a7db-10e706a086c9)

**Comment by frostime** [comment]
> 我感觉翻译会比较容易看，写味就是中文：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/336342762-bb088c13-995a-4d5e-a7db-10e706a086c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODU2NzMsIm5iZiI6MTcxNzQ4NTM3MywicGF0aCI6Ii83ODQzNDgyNy8zMzYzNDI3NjItYmIwODhjMTMtOTk1YS00ZDVlLWE3ZGItMTBlNzA2YTA4NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA3MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDg4YmViNTdjZjQ5NzhjYjg3YjI2NjNjYzliNTMzNjNkYmNiMzU3OThkZTc4NTM1Y2UwMWFkYjZlOTQ3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b1pd0nxZa3tB9ZcqkAm6nPMjnT2WWkMma8c723gflqc)

你要是觉得的确有必要，我可以抽空额外添加一下

**Comment by TCOTC** [comment]
虽然英文也很简单，但就是感觉不太直观，选择的时候会犹豫一下
