### ISSUE TITLE
需要一个配置项，不添加在菜单里

### ISSUE THREAD

**Issue by TCOTC** [frostime/sy-bq-callout#7]
![image](https://github.com/frostime/sy-bq-callout/assets/78434827/3226618d-b24b-4ff9-9502-7360db5e7477)

**Comment by frostime** [comment]
啥意思？没听明白。

**Comment by TCOTC** [comment]
插件提供一个配置项：`` 将 Callout 添加到 `/` 菜单中 `` ，然后就可以关闭菜单里加的这些 Callout

**Comment by frostime** [comment]
> 插件提供一个配置项：`` 将 Callout 添加到 `/` 菜单中 `` ，然后就可以关闭菜单里加的这些 Callout

这是遵循同一个设置配置的两种不同的输入方式。每个被启用的 callout 都既可以通过 / 创建，又可以通过点击块菜单进行更改。

你说的这个功能我不认为有必要性，先不做考虑了。

**Comment by TCOTC** [comment]
在菜单加了这些之后，就需要滚动菜单了，所以我想去掉：（简单来说就是跟 Savor 主题冲突）

[滚动.webm](https://github.com/frostime/sy-bq-callout/assets/78434827/9976880c-7997-47c9-83b8-15d646c551f5)

**Comment by frostime** [comment]
> 在菜单加了这些之后，就需要滚动菜单了：（简单来说是跟 Savor 主题冲突）
> 
>  default.webm

这种样式冲突更多是主题的问题，而不是插件的。

目测原因在于主题写 `/` 菜单样式的时候把菜单的宽度写为固定的。导致一旦插件注册的命令数量多起来，就会超过最大宽度，然后把容器的高度撑高了。

![image](https://github.com/frostime/sy-bq-callout/assets/27268127/1c73bda6-5336-49ae-8ba2-66db2b6cf7cd)

换句话说，只要插件注册的 / 命令数量多了以后，就肯定会出现这种问题。这不是某一个插件的问题。就算我在 Callout 插件里费心思处理这种问题，只要你安装别的插件也同样可能会遇到这种问题。

**Comment by TCOTC** [comment]
所以我没有装那些在菜单里加东西的插件
